# Generated by Django 2.0.7 on 2018-08-31 20:49

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hirek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('ShortDescription', tinymce.models.HTMLField(max_length=600)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('NewsPic', models.ImageField(upload_to='hirek')),
                ('Description', tinymce.models.HTMLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Programok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('ShortDescription', tinymce.models.HTMLField(max_length=600)),
                ('Date', models.DateTimeField()),
                ('EventPic', models.ImageField(upload_to='programok')),
                ('Location', models.CharField(max_length=256)),
                ('Length', models.CharField(max_length=256)),
                ('Category', models.CharField(max_length=256)),
                ('Description', tinymce.models.HTMLField(max_length=2000)),
            ],
        ),
    ]
