# Generated by Django 2.0.7 on 2018-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamogatok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponsorPic', models.ImageField(upload_to='sponsors')),
            ],
        ),
    ]
