# Generated by Django 2.0.7 on 2018-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tamogatok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerPic', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
